// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlcdb

import (
	"time"
)

// User represents a row in the users table.
type User struct {
	ID   uint32    `json:"id"`
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}
