// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: query.sql

package sqlcdb

import (
	"context"
	"time"
)

// Querier is the interface that all generated query sets implement.
type Querier interface {
	CountUsers(ctx context.Context) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (int64, error)
	DeleteUser(ctx context.Context, id uint32) error
	GetUserByID(ctx context.Context, id uint32) (User, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

// -----------------------------------------------------------------------
// CreateUser
// -----------------------------------------------------------------------

const createUser = `-- name: CreateUser :execresult
INSERT INTO users (name, dob)
VALUES (?, ?)
`

// CreateUserParams holds the parameters for the CreateUser query.
type CreateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
}

// CreateUser inserts a new user and returns the last-insert ID.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createUser, arg.Name, arg.Dob)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

// -----------------------------------------------------------------------
// GetUserByID
// -----------------------------------------------------------------------

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, dob
FROM users
WHERE id = ?
LIMIT 1
`

// GetUserByID fetches a single user by primary key.
func (q *Queries) GetUserByID(ctx context.Context, id uint32) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var u User
	err := row.Scan(&u.ID, &u.Name, &u.Dob)
	return u, err
}

// -----------------------------------------------------------------------
// UpdateUser
// -----------------------------------------------------------------------

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET name = ?,
    dob  = ?
WHERE id = ?
`

// UpdateUserParams holds the parameters for the UpdateUser query.
type UpdateUserParams struct {
	Name string    `json:"name"`
	Dob  time.Time `json:"dob"`
	ID   uint32    `json:"id"`
}

// UpdateUser updates name and dob for the given user ID.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser, arg.Name, arg.Dob, arg.ID)
	return err
}

// -----------------------------------------------------------------------
// DeleteUser
// -----------------------------------------------------------------------

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = ?
`

// DeleteUser removes a user by primary key.
func (q *Queries) DeleteUser(ctx context.Context, id uint32) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

// -----------------------------------------------------------------------
// ListUsers
// -----------------------------------------------------------------------

const listUsers = `-- name: ListUsers :many
SELECT id, name, dob
FROM users
ORDER BY id
LIMIT ?
OFFSET ?
`

// ListUsersParams holds the parameters for the ListUsers query.
type ListUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

// ListUsers returns a paginated slice of users.
func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []User
	for rows.Next() {
		var u User
		if err := rows.Scan(&u.ID, &u.Name, &u.Dob); err != nil {
			return nil, err
		}
		items = append(items, u)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

// -----------------------------------------------------------------------
// CountUsers
// -----------------------------------------------------------------------

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

// CountUsers returns the total number of users.
func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}
